version: '3.8'
services:

  java-lab3:
    image: alenkaksa81/java-lab3
    ports:
      - '8787:8787'

  oracle-db:
    image: alenkaksa81/oracle:21.3.0-xe
    container_name: oracle21xe
    restart: always
    volumes:
      - dbdata:/opt/oracle/oradata
    ports:
      - '1521:1521'
      - '5501:5500'
    environment:
      ORACLE_PWD: Ksa04061981



  java-lab2:
    build: .
    restart: on-failure
    ports:
      - '9345:9345'
    depends_on:
      - oracle-db
      - java-lab3
    environment:
      SPRING_DATASOURSE_URL: jdbc:oracle:thin:@//oracle-db:1521/XE
      SPRING_DATASOURSE_USERNAME: system
      SPRING_DATASOURSE_PASSWORD: Ksa04061981
      SPRING_DATASOURSE_DRIVER-CLASS-NAME: oracle.jdbc.OracleDriver

volumes:
  dbdata: