CREATE TABLE LAB2_EK_CATEGORIES
(CAT_ID   NUMBER(*,0) GENERATED ALWAYS AS IDENTITY,
CAT_NAME  VARCHAR2(64 BYTE) NOT NULL ENABLE,
CAT_DISCOUNT NUMBER(*,0),
CONSTRAINT "CATEGORY_PK" PRIMARY KEY ("CAT_ID"));

CREATE TABLE LAB2_EK_PRODUCER
(PROD_ID NUMBER(*, 0) GENERATED ALWAYS AS IDENTITY
    , PROD_NAME VARCHAR2(20 BYTE) NOT NULL
    , PROD_COUNTRY VARCHAR2(20 BYTE) NOT NULL
    , CONSTRAINT PRODUCER_PK PRIMARY KEY (PROD_ID));

CREATE TABLE LAB2_EK_CUSTOMER
(CUST_ID NUMBER(*, 0) GENERATED ALWAYS AS IDENTITY,
 CUST_NAME VARCHAR2(168 BYTE) NOT NULL,
 CUST_PHONE VARCHAR2(168 BYTE)  NOT NULL,
 CONSTRAINT "CUSTOMER_PK" PRIMARY KEY("CUST_ID"));

CREATE TABLE LAB2_EK_TOOLS
(TOOL_ID NUMBER(*, 0) GENERATED ALWAYS AS IDENTITY
, TOOL_MODEL VARCHAR2(64 BYTE) NOT NULL
, TOOL_TITLE VARCHAR2(168 BYTE) NOT NULL
, TOOL_PRICE NUMBER(*, 0) NOT NULL
, TOOL_CURRENCY VARCHAR2(64 BYTE) NOT NULL
, CAT_ID NUMBER NOT NULL
, PROD_ID NUMBER(*, 0) NOT NULL
, CONSTRAINT TOOLS_PK PRIMARY KEY (TOOL_ID)
,CONSTRAINT CATEGORY_FK FOREIGN KEY (CAT_ID)
REFERENCES LAB2_EK_CATEGORIES(CAT_ID)
, CONSTRAINT PRODUCER_FK FOREIGN KEY (PROD_ID)
REFERENCES LAB2_EK_PRODUCER(PROD_ID));

CREATE TABLE LAB2_EK_ORDERS
(ORD_ID NUMBER(*, 0) GENERATED ALWAYS AS IDENTITY
, CUST_ID NUMBER(*, 0) NOT NULL
, ORD_DATE DATE NOT NULL
, TOOL_ID NUMBER(*, 0)
, ORD_QUANTITY NUMBER NOT NULL
, CONSTRAINT ORDERS_PK PRIMARY KEY (ORD_ID)
,CONSTRAINT TOOL_FK FOREIGN KEY (TOOL_ID)
  REFERENCES LAB2_EK_TOOLS(TOOL_ID)
, CONSTRAINT CUSTOMER_FK FOREIGN KEY (CUST_ID)
  REFERENCES LAB2_EK_CUSTOMER(CUST_ID));
commit;
