CREATE TABLE LAB2_EK_CATEGORIES
(CAT_ID   NUMBER(*,0) GENERATED ALWAYS AS IDENTITY,
CAT_NAME  VARCHAR2(64 BYTE) NOT NULL ENABLE,
CAT_DISCOUNT NUMBER(*,0),
CONSTRAINT "CATEGORY_PK" PRIMARY KEY ("CAT_ID"));
CREATE TABLE LAB2_EK_TOOLS
(TOOL_ID NUMBER(*, 0) GENERATED ALWAYS AS IDENTITY
, TOOL_MODEL VARCHAR2(64 BYTE) NOT NULL
, TOOL_TITLE VARCHAR2(168 BYTE) NOT NULL
, TOOL_PRICE NUMBER(*, 0) NOT NULL
, CAT_ID NUMBER NOT NULL
, PROD_ID NUMBER(*, 0) NOT NULL
, CONSTRAINT TOOLS_PK PRIMARY KEY (TOOL_ID)
,CONSTRAINT CATEGORY_FK FOREIGN KEY (CAT_ID)
REFERENCES LAB2_EK_CATEGORIES(CAT_ID)
, CONSTRAINT PRODUCER_FK FOREIGN KEY (PROD_ID)
REFERENCES LAB2_EK_PRODUCER(PROD_ID));